<?php

namespace Como\FormBuilderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WidgetOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetOptionRepository extends EntityRepository
{
}
