Como\FormBuilderBundle\Entity\Form:
    properties:
        title:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~

Como\FormBuilderBundle\Entity\Field:
    properties:
        fieldLabel:
            - NotBlank: ~
        fieldLength:
            - NotBlank: ~
