Como\FormBuilderBundle\Entity\Form:
    type: entity
    table: form_builder_form
    repositoryClass: Como\FormBuilderBundle\Entity\FormRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        thankYouType:
            type: string
            length: 255
            column: thank_you_type
        thankYouExternalPage:
            type: string
            length: 255
            nullable: true
            column: thank_you_external_page
        thankYouMessage:
            type: text
            nullable: true
            column: thank_you_message
        fields:
            type: text
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    oneToOne:
        thankYouInternalPage:
            targetEntity: Application\Sonata\PageBundle\Entity\Page
            nullable: true
    lifecycleCallbacks:
        prePersist: [prePersist]
        preUpdate: [preUpdate]
